name: cslr2
channels:
  - defaults
dependencies:
  - python=3.9.16
  - pytorch==1.12.1
  - torchvision==0.13.1
  - cudatoolkit=11.6
  - pandas=1.5.3
  - einops=0.6.0
  - humanize=4.6.0
  - tqdm=4.65.0
  - pip
  - pip:
    - hydra-core==1.3.2
    - matplotlib==3.7.1
    - plotly==5.14.1
    - nltk==3.8.1
    - seaborn==0.12.2
    - sentence-transformers==2.2.2
    - wandb==0.14.0
    - lmdb
    - tabulate
    - opencv-python==4.7.0.72
