_target_: dataset.sentence.Sentences

# general parameters to load sentences associated to subtitles
subset2episode: ${paths.subset2episode}
subtitles_path: ${paths.subtitles_path}
subtitles_temporal_shift: 0.0
subtitles_max_duration: 20.0
subtitles_min_duration: 1.0
temporal_pad: 1.0
info_pkl: ${paths.info_pkl}
filter_stop_words: False
subtitles_random_offset: 0.5
fps: 25

# parameters to load video features
load_features: True
feats_lmdb: ${paths.vid_features_lmdb}
feats_load_stride: 1
feats_load_float16: False
feats_lmdb_window_size: 16
feats_lmdb_stride: 2
feats_dim: 768
video_augmentations: null

# parameters to load video pseudo-labels
load_pl: True
pl_lmdb: ${paths.annotations_pkl}
pl_load_stride: 1
pl_load_float16: False
pl_lmdb_window_size: 16
pl_lmdb_stride: 2
pl_filter: 0.6
pl_min_count: 6
pl_synonym_grouping: True
synonyms_pkl: ${paths.synonyms_pkl}
vocab_pkl: ${paths.vocab_pkl}

# parameters to load word embeddings
load_word_embds: True
word_embds_pkl: ${paths.word_embds_pkl}

# other parameters
verbose: False